spring:
  datasource:
    url: jdbc:mysql://172.16.4.165:3306/eshop?useUnicode=true&characterEncoding=utf8&SSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root0

server:
  port: 8080

servlet:
  context-path: /eshop

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.gary.ecommercewebsite.pojo

logging:
  level:
    com.gary.ecommercewebsite: info
  path: ./logs
